# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8b98a26128d8ba282f3e0cca692bc3e84f33828b3230f37fccbe992793565b3bfd9c74216598d64034e2d838800e0aa62196a342774df9e64dd0af18a37dd9fb

test:
  secret_key_base: a18085339d3d96c783d72fd0e40ae6ca4edcaa05480b841dd193c1f54322afc53f39696170fd0dad1445e8dc74bc94db27cb885bcb12f97477933f9421383579

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
